import type { Dish, Step } from "@/types"

export const dishes: Dish[] = [
  {
    id: "1",
    name: "番茄炒蛋",
    emoji: "🍅",
    image: "/dishes/tomato-egg.jpg",
    difficulty: "简单",
    time: "15分钟",
    calories: "280千卡",
    price: "¥12",
    category: "家常菜",
  },
  {
    id: "2",
    name: "红烧排骨",
    emoji: "🍖",
    image: "/dishes/ribs.jpg",
    difficulty: "中等",
    time: "45分钟",
    calories: "520千卡",
    price: "¥45",
    category: "硬菜",
  },
  {
    id: "3",
    name: "麻婆豆腐",
    emoji: "🧈",
    image: "/dishes/mapo-tofu.jpg",
    difficulty: "中等",
    time: "25分钟",
    calories: "350千卡",
    price: "¥18",
    category: "川菜",
  },
  {
    id: "4",
    name: "蛋炒饭",
    emoji: "🍳",
    image: "/dishes/fried-rice.jpg",
    difficulty: "简单",
    time: "10分钟",
    calories: "420千卡",
    price: "¥10",
    category: "主食",
  },
  {
    id: "5",
    name: "清炒时蔬",
    emoji: "🥬",
    image: "/dishes/greens.jpg",
    difficulty: "简单",
    time: "10分钟",
    calories: "120千卡",
    price: "¥10",
    category: "素菜",
  },
  {
    id: "6",
    name: "宫保鸡丁",
    emoji: "🍗",
    image: "/dishes/kungpao.jpg",
    difficulty: "中等",
    time: "30分钟",
    calories: "380千卡",
    price: "¥28",
    category: "川菜",
  },
  {
    id: "7",
    name: "酸辣土豆丝",
    emoji: "🥔",
    image: "/dishes/potato.jpg",
    difficulty: "简单",
    time: "15分钟",
    calories: "200千卡",
    price: "¥10",
    category: "家常菜",
  },
  {
    id: "8",
    name: "糖醋里脊",
    emoji: "🐷",
    image: "/dishes/sweet-sour.jpg",
    difficulty: "中等",
    time: "35分钟",
    calories: "460千卡",
    price: "¥35",
    category: "硬菜",
  },
  {
    id: "9",
    name: "牛肉面",
    emoji: "🍜",
    image: "/dishes/noodle.jpg",
    difficulty: "中等",
    time: "40分钟",
    calories: "550千卡",
    price: "¥25",
    category: "面食",
  },
  {
    id: "10",
    name: "凉拌黄瓜",
    emoji: "🥒",
    image: "/dishes/cucumber.jpg",
    difficulty: "简单",
    time: "5分钟",
    calories: "80千卡",
    price: "¥8",
    category: "凉菜",
  },
  {
    id: "11",
    name: "水煮鱼",
    emoji: "🐟",
    image: "/dishes/fish.jpg",
    difficulty: "困难",
    time: "50分钟",
    calories: "480千卡",
    price: "¥55",
    category: "川菜",
  },
  {
    id: "12",
    name: "饺子",
    emoji: "🥟",
    image: "/dishes/dumplings.jpg",
    difficulty: "中等",
    time: "60分钟",
    calories: "450千卡",
    price: "¥30",
    category: "面食",
  },
]

export const steps: Record<string, Step[]> = {
  "1": [
    { id: "1-1", dishId: "1", stepNumber: 1, content: "番茄切块，鸡蛋打散加少许盐搅匀" },
    { id: "1-2", dishId: "1", stepNumber: 2, content: "热锅凉油，倒入蛋液炒至凝固盛出" },
    { id: "1-3", dishId: "1", stepNumber: 3, content: "锅中再加油，放入番茄块翻炒出汁" },
    { id: "1-4", dishId: "1", stepNumber: 4, content: "倒回鸡蛋，加盐、糖调味，翻炒均匀出锅" },
  ],
  "2": [
    { id: "2-1", dishId: "2", stepNumber: 1, content: "排骨冷水下锅，加料酒姜片焯水去血沫，捞出洗净" },
    { id: "2-2", dishId: "2", stepNumber: 2, content: "锅中放油加冰糖，小火炒出糖色" },
    { id: "2-3", dishId: "2", stepNumber: 3, content: "下排骨翻炒上色，加生抽、老抽、料酒、八角、桂皮" },
    { id: "2-4", dishId: "2", stepNumber: 4, content: "加开水没过排骨，大火烧开转小火炖 30 分钟" },
    { id: "2-5", dishId: "2", stepNumber: 5, content: "大火收汁至浓稠，撒葱花出锅" },
  ],
  "3": [
    { id: "3-1", dishId: "3", stepNumber: 1, content: "嫩豆腐切 2cm 小块，开水加盐焯烫 2 分钟捞出" },
    { id: "3-2", dishId: "3", stepNumber: 2, content: "锅中放油，下牛肉末炒至酥香，加豆瓣酱炒出红油" },
    { id: "3-3", dishId: "3", stepNumber: 3, content: "加姜蒜末、豆豉炒香，倒入适量清水" },
    { id: "3-4", dishId: "3", stepNumber: 4, content: "放入豆腐小火煮 5 分钟入味，分次淋入水淀粉勾芡" },
    { id: "3-5", dishId: "3", stepNumber: 5, content: "出锅撒花椒粉和葱花" },
  ],
  "4": [
    { id: "4-1", dishId: "4", stepNumber: 1, content: "隔夜米饭用手捏散，鸡蛋打散备用" },
    { id: "4-2", dishId: "4", stepNumber: 2, content: "热锅多油，倒入蛋液快速划散" },
    { id: "4-3", dishId: "4", stepNumber: 3, content: "倒入米饭大火翻炒，用铲子压散结块" },
    { id: "4-4", dishId: "4", stepNumber: 4, content: "加盐、少许白胡椒粉，撒葱花翻炒出锅" },
  ],
  "5": [
    { id: "5-1", dishId: "5", stepNumber: 1, content: "时蔬洗净，蒜切末备用" },
    { id: "5-2", dishId: "5", stepNumber: 2, content: "热锅凉油，下蒜末爆香" },
    { id: "5-3", dishId: "5", stepNumber: 3, content: "放入时蔬大火快炒，加盐调味" },
    { id: "5-4", dishId: "5", stepNumber: 4, content: "断生即出锅，保持脆嫩口感" },
  ],
  "6": [
    { id: "6-1", dishId: "6", stepNumber: 1, content: "鸡胸肉切丁，加料酒、生抽、淀粉腌制 15 分钟" },
    { id: "6-2", dishId: "6", stepNumber: 2, content: "调碗汁：生抽、醋、糖、淀粉、水混合备用" },
    { id: "6-3", dishId: "6", stepNumber: 3, content: "热锅凉油下鸡丁滑炒至变色盛出" },
    { id: "6-4", dishId: "6", stepNumber: 4, content: "锅中下干辣椒、花椒、姜蒜爆香，加豆瓣酱炒出红油" },
    { id: "6-5", dishId: "6", stepNumber: 5, content: "倒回鸡丁和花生米，淋入碗汁大火翻炒均匀" },
  ],
  "7": [
    { id: "7-1", dishId: "7", stepNumber: 1, content: "土豆去皮切细丝，冷水浸泡洗去淀粉，沥干" },
    { id: "7-2", dishId: "7", stepNumber: 2, content: "干辣椒剪段，蒜切末" },
    { id: "7-3", dishId: "7", stepNumber: 3, content: "热锅凉油，下花椒、干辣椒、蒜末爆香" },
    { id: "7-4", dishId: "7", stepNumber: 4, content: "倒入土豆丝大火快炒，加醋、盐、少许糖" },
    { id: "7-5", dishId: "7", stepNumber: 5, content: "翻炒至断生即出锅，保持爽脆" },
  ],
  "8": [
    { id: "8-1", dishId: "8", stepNumber: 1, content: "猪里脊切条，加料酒、盐、蛋清腌制 15 分钟" },
    { id: "8-2", dishId: "8", stepNumber: 2, content: "面粉和淀粉 1:1 混合，里脊裹浆，六成油温炸至金黄捞出" },
    { id: "8-3", dishId: "8", stepNumber: 3, content: "调糖醋汁：番茄酱、白糖、白醋、清水混合" },
    { id: "8-4", dishId: "8", stepNumber: 4, content: "锅中少许油倒入糖醋汁煮至浓稠，倒入炸好的里脊快速翻匀" },
    { id: "8-5", dishId: "8", stepNumber: 5, content: "撒白芝麻出锅装盘" },
  ],
  "9": [
    { id: "9-1", dishId: "9", stepNumber: 1, content: "牛腱子冷水下锅焯水，捞出切厚片" },
    { id: "9-2", dishId: "9", stepNumber: 2, content: "锅中放油下葱姜、八角、桂皮、香叶炒香" },
    { id: "9-3", dishId: "9", stepNumber: 3, content: "加牛肉翻炒，放生抽、老抽、豆瓣酱调味" },
    { id: "9-4", dishId: "9", stepNumber: 4, content: "加开水大火烧开转小火炖 1.5 小时至软烂" },
    { id: "9-5", dishId: "9", stepNumber: 5, content: "另起锅煮面，捞入碗中浇上牛肉和汤，撒香菜" },
  ],
  "10": [
    { id: "10-1", dishId: "10", stepNumber: 1, content: "黄瓜洗净拍碎切段" },
    { id: "10-2", dishId: "10", stepNumber: 2, content: "蒜捣成泥，加盐、醋、生抽、香油、辣椒油调成料汁" },
    { id: "10-3", dishId: "10", stepNumber: 3, content: "将料汁浇在黄瓜上拌匀即可" },
  ],
  "11": [
    { id: "11-1", dishId: "11", stepNumber: 1, content: "草鱼片成薄片，加料酒、盐、蛋清、淀粉上浆" },
    { id: "11-2", dishId: "11", stepNumber: 2, content: "锅中放油下干辣椒、花椒、豆瓣酱炒出红油" },
    { id: "11-3", dishId: "11", stepNumber: 3, content: "加水烧开，先下豆芽、青菜焯烫铺碗底" },
    { id: "11-4", dishId: "11", stepNumber: 4, content: "转小火逐片下入鱼片，煮至变白连汤倒入碗中" },
    { id: "11-5", dishId: "11", stepNumber: 5, content: "鱼片上撒干辣椒段、花椒、蒜末，浇热油激香" },
  ],
  "12": [
    { id: "12-1", dishId: "12", stepNumber: 1, content: "面粉加水揉成光滑面团，醒面 30 分钟" },
    { id: "12-2", dishId: "12", stepNumber: 2, content: "肉馅加姜末、葱花、盐、生抽、香油搅打上劲" },
    { id: "12-3", dishId: "12", stepNumber: 3, content: "面团搓条切剂子，擀成中间厚边缘薄的圆皮" },
    { id: "12-4", dishId: "12", stepNumber: 4, content: "包入馅料捏紧封口" },
    { id: "12-5", dishId: "12", stepNumber: 5, content: "水烧开下饺子，点三次凉水，饺子浮起即可捞出" },
  ],
}

export function getSteps(dishId: string): Step[] {
  return steps[dishId] ?? []
}
